name: Build and Commit node-ui

on:
  workflow_dispatch: # Allow manual triggering of the workflow
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  build_node_ui:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Check if there are changes in the node-ui folder (excluding build)
      - name: Check for changes in node-ui (excluding build folder)
        id: check_changes
        run: |
          # Initialize the flag to false
          echo "CHANGES_DETECTED=false" >> $GITHUB_ENV

          # Check if HEAD^ exists (i.e., there are at least two commits)
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            # If HEAD^ exists, check for changes in the node-ui folder excluding the build directory
            if git diff --quiet HEAD^ HEAD -- 'node-ui' ':!node-ui/build'; then
              echo "No changes in node-ui (excluding build folder)."
            else
              echo "Changes detected in node-ui."
              echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
            fi
          else
            # If HEAD^ doesn't exist (only one commit), check for changes in the first commit
            if git diff-tree --no-commit-id --name-only -r HEAD -- 'node-ui' ':!node-ui/build' | grep .; then
              echo "Changes detected in node-ui."
              echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
            else
              echo "No changes in node-ui (excluding build folder)."
            fi
          fi

      # Explicit exit if no changes detected
      - name: Exit if no changes detected
        run: |
          if [ "$CHANGES_DETECTED" = "false" ]; then
            echo "No changes detected, exiting."
            exit 0
          fi

      # Set up Node.js and install pnpm
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies and build node-ui
      - name: Install frontend dependencies with pnpm
        run: pnpm install --prefix ./node-ui

      - name: Build node-ui
        run: pnpm --filter ./node-ui run build

      # Set up Git credentials for committing
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Add changes (build folder) and commit
      - name: Add and commit build folder
        run: |
          git add ./node-ui/build
          git commit --no-verify -m "Automated commit of node-ui build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push changes to the repository
      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
